spring.application.name=inventory




spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bhardwajanurag546@gmail.com
spring.mail.password=iwqrjyrfayayklxi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.security.enable-csrf=false







spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
spring.datasource.username = postgres
spring.datasource.password = root
spring.datasource.url = jdbc:postgresql://localhost:5432/kidbeaInventory





spring.security.oauth2.client.registration.google.client-id=1025878857238-ntg3j2969lvfndnvj102ej9mt8s6okn2.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub








